### ISSUE TITLE
Where can I see module documentation in the generated html?

### ISSUE THREAD

**Issue by RationalityFrontline** [Kotlin/dokka#1318]
**Question**
I downloaded the [dokka-gradle-example](https://github.com/Kotlin/kotlin-examples/tree/master/gradle/dokka/dokka-gradle-example) and ran the gradle task dokkaHtml, then I opened the generated html located at "build/dokka/html/-dokka -gradle -example/index.html", however I can't see any module documentation.  More specifically, I can't see the sentence "This is an example of how you can write module documentation with Dokka." which is defined in the Module.md file.

**Screenshots**
![image](https://user-images.githubusercontent.com/69410606/90352651-8c21a780-e076-11ea-99bc-af491e32318e.png)
![image](https://user-images.githubusercontent.com/69410606/90352759-d60a8d80-e076-11ea-8a56-f8eeeb01a336.png)

**Installation**
- Operating system: Windows
- Build tool: Gradle v6.5.1
- Dokka version: 1.4.0-rc

**Comment by sellmair** [comment]
I am not sure if this is misconfigured or a bug. Thanks for reporting. This is in the queue now 👍

**Comment by sellmair** [comment]
Might also be related to #1322

**Comment by BarkingBad** [comment]
Hi @RationalityFrontline,

sorry for a long response time. The problem is with naming. There is overriden module name to `Dokka Gradle Example` in `build.gradle.kts`. To resolve issue with linking the module description you can either:
* change `moduleDisplayName` to point to be `moduleDisplayName.set("dokka-gradle-example")` or completely remove it since it is already name of the module
* change in `Module.md` header to point to the overriden name, e. g. `# Module Dokka Gradle Example`

Please note that in dokka version `1.4.10` property will change name from `moduleDisplayName` to `moduleName`

![obraz](https://user-images.githubusercontent.com/32793002/92741671-237cd080-f37f-11ea-9964-381b0e611412.png)


I hope this answer satisfy you. Thank you again for reporting that issue
