### ISSUE TITLE
Encourage users to update dokka

### ISSUE THREAD

**Issue by MarcinAman** [Kotlin/dokka#1436]
The goal of this task is to provide a solution encouraging users to update their dokka. As we see in bintray graph a lot of them are still using older versions. 

I think there are 2 steps:
 - automatically informing about new dokka version. This can be done either on a separate task or during dokka build.
 - think if it is a good and feasible idea to have something to automatically bump version for a user and change configuration accordingly. Ofc user should have an ability to enable/disable that feature.

**Comment by xerus2000** [comment]
I think the best encouragement would be extensive documentation :)

Multiple times I have tried updating dokka and stopped because I grew frustrated. DokkaMultiModuleTask and the like have no place in the official documentation. I still get `@see` spams. Yes, I usually report these things, but sometimes you ain't got the energy for that.

**Comment by tprochazka** [comment]
I spent already two days trying to update from 0.10.1 to 1.4.0 .
And I'm still not able to make it running in my setup
https://github.com/Kotlin/dokka/issues/1280#issuecomment-690761116
Maybe I should create a new issue for that?

A completely rewritten and much more complicated configuration is another reason why peoples don't want to do it.
