### ISSUE TITLE
Dokka plugin in external project

### ISSUE THREAD

**Issue by msink** [Kotlin/dokka#1471]
**Question**
Trying to setup minimal Dokka plugin in external project - as first step copy-pased from JekyllPlugin:

```kt
class MyGfmPlugin : DokkaPlugin() {

    val gfmPreprocessors by extensionPoint<PageTransformer>()

    val renderer by extending {
        (CoreExtensions.renderer
                providing { MyGfmRenderer(it) }
                override plugin<GfmPlugin>().renderer)
    }

    val rootCreator by extending {
        gfmPreprocessors with RootCreator
    }

    val packageListCreator by extending {
        gfmPreprocessors providing {
            PackageListCreator(it, RecognizedLinkFormat.DokkaGFM)
        } order { after(rootCreator) }
    }
}

class MyGfmRenderer(
    context: DokkaContext
) : CommonmarkRenderer(context) {

    override val preprocessors = context.plugin<MyGfmPlugin>().query { gfmPreprocessors }

    override fun buildPage(page: ContentPage, content: (StringBuilder, ContentPage) -> Unit): String {
        val builder = StringBuilder()
        //builder.append("---\n")
        //builder.append("title: ${page.name} -\n")
        //builder.append("---\n")
        content(builder, page)
        return builder.toString()
    }
}
```
It sort of works, but `SouceSet`s are not merged:
What I'm missing?

**Screenshots**
![dokka](https://user-images.githubusercontent.com/1785275/93094951-f7818800-f6bb-11ea-8ef0-40e384fcdb30.png)

**Installation**
- Clone https://github.com/msink/kotlin-libui/, checkout branch `dokka`
- Operating system: Windows
- `gradlew dokkaMy`

**Comment by BarkingBad** [comment]
Does this problem exist while using predefined plugins and tasks e. g. `dokkaGfm` or `dokkaJekyll`. 

However, it looks like wrong setup of sourceSets. Could you provide your build config, as well as make sure that you have `commonSourceSet` for your `windows` and `windows64` and you have correctly marked classes with `expect`/`actual` keywords. Such behaviour (appending sourceSetName to file name) means that from compiling point of view these classes are completely independent (have its own meaning in context of given sourceSet) but their pages are clashing for path location.

**Comment by msink** [comment]
Looks like something was broken in Dokka 1.4.10-dev-70

Same setup with 1.4.10-dev-69 works just fine

To reproduce:
replace "1.4.10-dev-70" to "1.4.10-dev-69" in build.gradle.kts and tools/dokka-mygfm/build.gradle.kts

**Comment by BarkingBad** [comment]
Hey, I'm sorry, I accidentally skipped footer with repository and branch.

What you see as a bug is, as I said, desired behaviour. So far, we were merging all elements from different sourceSets if they seemed to be complimentary (as we assumed they were probably `expect`/`actuals`). However, you can have for multiplatfrom project elements that share same fully qualified name, but are completely unrelated - thus **should not be merged**. For such cases we have to create different pages, so we append unique sourceSet name as a tiebreaker. 

In your configuration I see given sourceSets and their relation: `common (root)` (default sourceSet), then `windows (leaf)`, `windows64 (leaf)`, `linux (leaf)`, `macos (leaf)`

But all leafs have their own `sourceRoots`. Dokka doesn't know these are exactly same files. For dokka, these are elements that don't are in `expect`/`actual` relation, and since they are clashing fully qualified name, they should not be merged.

How to fix that?

I think you should create `commonNative` then make relation like this:
```
               +---------+
               | common  |
               +---+-----+
                   ^
                   |
        +----------+---------------+
        |      commonNative        |   <-- HERE LOCATE ALL SOURCE ROOTS
        ++-------+-------------+---+
         ^       ^             ^  ^-----+
         |       |             |        |
+--------++   +--+------+   +--+--+   +-+---+
| windows |   |windows64|   |macos|   |linux|
+---------+   +---------+   +-----+   +-----+
```

given that, you can just run `dokka` task without any magic that I used in that PR https://github.com/msink/kotlin-libui/pull/37

**Comment by msink** [comment]
Unfortunately `interop` tool does not yet support that setup, if I get you right.
So for now - let's keep your hack, and do refactoring later.

**Comment by BarkingBad** [comment]
I'm not proficient with `Kotlin/Native` and `cinterop`, but I think you can do it right now. I just didn't want to mess with your config other than dokka, but here is my proposal as I see it fit. https://github.com/msink/kotlin-libui/pull/38 

Docs look good, however you should check if project builds well

**Comment by msink** [comment]
It works from Gradle command line, but when opened in IDEA 2020.2.1 - everyting is red and even "Kotlin not configured".
Surely it's not related to Dokka, but somethig in tooling is still not ready... (If I not missed somethig).
So for now - let's keep your first PR and postpone second.

**Comment by BarkingBad** [comment]
It is really weird, as for me (IDEA Ultimate 2020.2.2 RC) it works well. Yeah, surely, this one was just proposal how to change configuration structure, you can change it to suit your usecase. As I believe, now everything is alright, I'll close the issue.
![obraz](https://user-images.githubusercontent.com/32793002/93223363-4688f500-f770-11ea-802d-c78ba7beca3d.png)
