### ISSUE TITLE
Dokka regularly OOMs gradle in a simple project

### ISSUE THREAD

**Issue by ZacSweers** [Kotlin/dokka#1508]
**Describe the bug**
I have a small project that, when I run all the dokkaHtml tasks on my relatively powerful personal machine, easily exhausts Gradle's default memory configuration for a build

**Expected behaviour**
I understand nothing is free, but I think Dokka shouldn't OOM a trivial project and my first thought was there might be a memory leak.

**Screenshots**
N/A

**To Reproduce**
Check out [this project](https://github.com/ZacSweers/MoshiX) and run `./gradlew dokkaHtml` locally

**Dokka configuration**
Standard configuration

**Installation**
- Operating system: macOS
- Build tool: Gradle 6.6
- Dokka version: 1.4.10

**Additional context**
Add any other context about the problem here

**Comment by ZacSweers** [comment]
Example failure https://github.com/ZacSweers/MoshiX/runs/1173513315

**Comment by Kordyjan** [comment]
This duplicates #1405. It is worth noting that it is not a simple memory leak because jvm is running out of metaspace and not heap space. We are still investigating that. We had a few ideas where it is coming from but all of them turned out to be false.

For now you can increase your metaspace as a workaround. Just put `org.gradle.jvmargs=-XX:MaxMetaspaceSize=512m` in `gradle.properties`. For some bigger projects `1G` may be necessary instead of `512m`.
