### ISSUE TITLE
[1.4.20-multimodule-dev-3] Deprecated methods are not skipped 

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/dokka#1525]
**Describe the bug**

We have dokka configured to ignore deprecated declarations:
```
perPackageOption {
    prefix.set("kotlinx.serialization")
    reportUndocumented.set(false)
    skipDeprecated.set(true)
}
```

But we still have them in the resulting output.
Example:
Declaration -- https://github.com/Kotlin/kotlinx.serialization/blob/dokka-fixed-revisions/formats/json/jsMain/src/kotlinx/serialization/DynamicsMigration.kt#L47
Site -- https://kotlin.github.io/kotlinx.serialization/kotlinx-serialization-json/kotlinx-serialization-json/kotlinx.serialization.html

**Expected behaviour**

Deprecations are omitted from the resulting site

**Screenshots**

**To Reproduce**
`kotlinx-serialization` project, branch `dokka-fixed-revisions`, `./gradlew dokkaHtmlMultiModule`

**Dokka configuration**

https://github.com/Kotlin/kotlinx.serialization/blob/dokka-fixed-revisions/gradle/dokka.gradle#L17

**Installation**
- Operating system: macOS
- Build tool: Gradle 6.3
- Dokka version: 1.4.20-multimodule-dev-3

**Comment by MarcinAman** [comment]
Hi, i think the issue is related to the fact, that in multimodule story we changed the name of the dokka task from `dokkaHtml` to `dokkaHtmlPartial` so it requires a change in configuration in: https://github.com/Kotlin/kotlinx.serialization/blob/317ff196d9098632aa163b12b2d8e720e634d2f0/gradle/dokka.gradle#L17

After changing this line i think everything is ok
