### ISSUE TITLE
documentation gradle tasks crash on symbols with asterisk

### ISSUE THREAD

**Issue by DetachHead** [Kotlin/dokka#1551]
**Describe the bug**
symbols with an asterisk cause the following error when running `dokkaJekyll` or `dokkaHtml` tasks

```
Failed to write org.jetbrains.dokka.base.renderers.FileWriter@4f044a0f. Illegal char <*>
```

**Expected behaviour**
documentation is generated successfully

**Screenshots**
If applicable, add screenshots to help explain your problem
![image](https://user-images.githubusercontent.com/57028336/95753147-83e79080-0ce4-11eb-81a1-944d272758c6.png)

**To Reproduce**
1. clone https://github.com/DetachHead/kotlinxpath/tree/dokka-issue-eg
2. run one of the documentation gradle tasks

**Dokka configuration**
whatever the default is, i didn't change anything

**Installation**
- Operating system: Windows 10
- Build tool: Gradle v6.5.1
- Dokka version: 1.4.10

**Comment by MarcinAman** [comment]
Hi, i think the issue is resolved on current master branch. Would you like to use our nightly builds to check if everything is fine?

To use nightly build add `maven("https://maven.pkg.jetbrains.space/kotlin/p/dokka/dev")` to your repositories. [Here]( https://maven.pkg.jetbrains.space/kotlin/p/dokka/dev/org/jetbrains/dokka/dokka-core/maven-metadata.xml) you can see a list of available versions. You would be interested in the latest one from the 1.4.20 branch, for example: `1.4.20-dev-10`

**Comment by DetachHead** [comment]
i can't seem to get gradle to find any of the packages on that repository.
![image](https://user-images.githubusercontent.com/57028336/95762830-95836500-0cf1-11eb-9e0b-2a39a6929ee9.png)

### build.gradle.kts
```kotlin
plugins {
    kotlin("multiplatform") version "1.4.0"
    id("org.jetbrains.dokka") version "1.4.20-dev-8"
    `maven-publish`
}
```
### settings.gradle.kts
```kotlin
pluginManagement {
    repositories {
        maven("https://dl.bintray.com/kotlin/kotlin-eap")
        mavenCentral()
        maven("https://plugins.gradle.org/m2/")
        maven("https://maven.pkg.jetbrains.space/kotlin/p/dokka/dev")
    }
}
```

**Comment by DetachHead** [comment]
nevermind, got it working. issue is indeed fixed in the latest build
