### ISSUE TITLE
Handling @code tag

### ISSUE THREAD

**Issue by MarcinAman** [Kotlin/dokka#1564]
For example: 
```
Identifies calls to {@code assertThat} and similar methods inside the implementation of a {@code * Subject} assertion method. These calls should instead use {@code check(...)}.

{@code * // Before: * public void hasFoo() { * assertThat(actual().foo()).isEqualTo(expected); * } * * // After: * public void hasFoo() { * check("foo()").that(actual().foo()).isEqualTo(expected); * } * }
```
should be parsed and not left as a text

**Comment by owengray-google** [comment]
Some specific issues that Exoplayer (one of the Google libraries currently trying to use dokka) noted:
1. `"{@code "` present in Text Documentable / output
2. In [Exoplayer2/Player.java](https://github.com/google/ExoPlayer/blob/release-v2/library/common/src/main/java/com/google/android/exoplayer2/Player.java), _Single-line_ code tags wrapped for length include `*`:
```
   * Returns the reason why playback is suppressed even though {@link #getPlayWhenReady()} is {@code
   * true}, or {@link #PLAYBACK_SUPPRESSION_REASON_NONE} if playback is not suppressed.
```
has the code tag render as `{@code * true}`, picking up the `*`.
3. _Multiline_ code tags don't retain whitespace, e.g. in [Exoplayer2/DefaultTrackSelector.java](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/trackselection/DefaultTrackSelector.java)
```
 * <pre>{@code
 * trackSelector.setParameters(
 *     trackSelector
 *         .buildUponParameters()
 *         .setMaxVideoSizeSd()
 *         .setPreferredAudioLanguage("deu"));
 * }</pre>
```
The result is all compressed onto one line.

It's really not obvious how (3) and (2) should be solved together though--how do you distinguish intended-multiline-code-tags from intended-single-line ones? When is a newline in a code tag due to something being too long for one line, and when is it intentional whitespace for formatting.
I have the impression that people's first instinct is to want doclava behavior replicated, though I'm not sure what that is.
Looking at the code examples above, the best signal might be if the code tag contains more newlines/whitespace chars than #characters//80 + 1? However, plenty of other heuristics might work, or be superior, such as simple total # of characters or whether indenting whitespace is present on any line.

**Comment by MarcinAman** [comment]
Speaking about 2 and 3: we should follow the same algorithm as javadoc has therefore if code is wrapped only in `{@code }` then we treat it as inline. If user also added `<pre>{@code }</pre>` then we should keep the formatting. Examples that you posted look like this in newest dev version of dokka:
![image](https://user-images.githubusercontent.com/15652452/129906113-024cf9f1-786d-440f-9e78-e0404d8ed5c2.png)

You can check out other edge cases that we have discussed on PR's page: https://github.com/Kotlin/dokka/pull/2059
