### ISSUE TITLE
Side menu is collapsed

### ISSUE THREAD

**Issue by MarcinAman** [Kotlin/dokka#1565]
Example of that is `FactoryMethodName` in https://github.com/google/error-prone
in error_prone_core/com.google.errorprone.bugpatterns/ChainedAssertionLosesContext/FactoryMethodName

**Comment by IgnatBeresnev** [comment]
[FactoryMethodName](https://github.com/google/error-prone/blob/f112765ae5ebd389e2427d0aee23738bc41939bf/core/src/main/java/com/google/errorprone/bugpatterns/ChainedAssertionLosesContext.java#L183) is a nested class which weren't rendered in navigation at all up until Dokka 1.7.20, so it didn't know which navigation element to choose.

This should've been fixed in Dokka 1.7.20, so I'm closing the issue as fixed.
