### ISSUE TITLE
Generate kdocs for generated code

### ISSUE THREAD

**Issue by bhaktasatapathy** [Kotlin/dokka#1585]
**Question**
I am generating code by using Annotation processor and Kotlinpoet. Once I generate code I want to generate kdocs for the same. I tried many things but still its not considering kotlin generated classes for documentation generation. Is there any way I can achieve the same?

**Screenshots**
NA

**Installation**
- Operating system: macOS
- Build tool: Gradle v6.1.1
- Dokka version: 1.4.10

**Additional context**
NA

**Comment by MarcinAman** [comment]
Hi, 
i don't fully understand if you mean generating kdocs (in code) or documentation for it. 
For the first case: it is not possible, dokka does not generate documentation automatically, it doesn't even change the sourcecode. 
In the second case: I think it should be doable. If the library you are using outputs `.kt` files dokka should be able to process them. Please keep in mind that they need to be generated **before** dokka run, otherwise they wont be seen.

If you have any more trouble with it please give create (or post a link) to a project that you are working on, I'll try to help
