### ISSUE TITLE
Some Gradle exceptions are silently swallowed

### ISSUE THREAD

**Issue by drewhannay** [Kotlin/dokka#1603]
**Describe the bug**
When configuring Dokka source links in a Groovy build script, syntax / type errors are swallowed by Dokka and tasks still pass despite internally failing with various exceptions. Source links are not added to generated documentation.

**Expected behaviour**
Syntax errors in the build scripts should cause the Dokka Gradle tasks to fail and should surface the underlying exception to users.

**To Reproduce**
Here's a sample project that reproduces the issue:
https://github.com/drewhannay/dokka-repros/tree/sourceLinkExceptionSwallowing

Just check out that branch and run `./gradlew dokkaHtml` to see that the task passes despite the syntax errors in `build.gradle`

**Installation**
- Operating system: macOS
- Build tool: Gradle v6.7, Groovy build scripts
- Dokka version: 1.4.10.2

**Comment by MarcinAman** [comment]
@kamildoleglo could you take a look what we can do here?

**Comment by IgnatBeresnev** [comment]
I believe this has since been resolved, I'm getting errors when using configuration provided in your reproducer (thanks for that!)

Although the errors are not really descriptive and don't tell you what exactly is wrong, they show the correct line number:
```
* Where:
Build file '/home/ignat/IdeaProjects/dokka-debug-groovy/build.gradle' line: 58

* What went wrong:
Execution failed for task ':dokkaHtml'.
> Error while evaluating property 'unsuppressedSourceSets' of task ':dokkaHtml'
   > Could not create domain object 'test' (GradleDokkaSourceSetBuilder)
```

After fixing the mistakes (`.set()` instead of ` = ` and adding `new` keyword to URL), `dokkaHtml` completes just fine

Do tell us if you keep experiencing this problem!
