### ISSUE TITLE
Does it work with java only?

### ISSUE THREAD

**Issue by Andre601** [Kotlin/dokka#1707]
**Question**
I would like to know, if this piece of software is actually supporting Projects that are Java only, meaning they don't utilize Kotlin in their code and also use a normal `build.gradle` and not the kotlin equivalent.

**Screenshots**

**Installation**
- Operating system: Windows 10 (64-Bit)
- Build tool: Gradle 5.5
- Dokka version: N/A (Currently not using it)

**Additional context**
I like the idea behind this software and the additional amount of features it seems to support (Which from what I gathered is features such as markdown within comments for formatting), but I don't want to turn my Java project in a kotlin one just to use this tool, so I want to first find out if this tool supports 100% Java projects, or if there are other projects that offer similar functionalities and features like this one.

Also: How do some docs actually look like? If you have some live examples would I love to see them.

**Comment by kamildoleglo** [comment]
Yes and yes, however you have to have the `kotlin` plugin applied in the `build.gradle` file I believe, because we depend on the Kotlin plugin providing the source roots, and classpath, and other stuff.
Kotlinx.serialization uses Dokka's HTML format for example: https://kotlin.github.io/kotlinx.serialization/ , but there are several Dokka examples here: https://github.com/Kotlin/kotlin-examples/tree/master/gradle/dokka so you can just clone the repo and check them out yourself

**Comment by Andre601** [comment]
Okay. Thanks for letting me know.

How would the setup look like if I want to keep Java-like Docs and use a build.gradle and not a build.gradle.kts?
I assume I would need to use the kotlinAsJava module for this, or would it by default generate Java-like looking docs?

**Comment by kamildoleglo** [comment]
Kind of the same really (you can refer to the kotlinx.serialization as they use Groovy files), you have to add dokka to the `plugins` block (and `kotlin` probably) and add the kotlinAsJava plugin in the dependencies (eg. using the `dokkaHtmlPlugin` configuration)

**Comment by Andre601** [comment]
Thanks again for the info. Will now look into how I can implement this and may respond again if I need more help.
