### ISSUE TITLE
Multi-module root page links

### ISSUE THREAD

**Issue by cromefire** [Kotlin/dokka#1719]
**Is your feature request related to a problem? Please describe**
Currently, the side menu only lists "Modules" and then individual module menus. As consequence you can't navigate back from a module to the root page/"homepage" (module overview).

**Describe the solution you'd like**
There would be 2 solutions from my point of view:
1. The best solution would be a "proper" module-wide (probably a lot of work and related to #1402)
2. Add a root page link, for example at the logo (maybe generally a good idea, also in non-multimodule cases?)

**Describe alternatives you've considered**
None, so far.

**Additional context**
![image](https://user-images.githubusercontent.com/26320625/106628769-6fbced00-657a-11eb-8ba6-504d54e6b7db.png)

**Comment by MarcinAman** [comment]
Hi, our multimodule has changed since the last release. You can try out the new one on the nightly build by adding a custom resolver: `maven("https://maven.pkg.jetbrains.space/kotlin/p/dokka/dev")` and changing version to: `1.4.20.2-dev-62`. 

Please let me know what you think and if you encounter any problems

**Comment by cromefire** [comment]
That look pretty well indeed
