### ISSUE TITLE
Option to add github corners

### ISSUE THREAD

**Issue by elect86** [Kotlin/dokka#1732]
**Is your feature request related to a problem? Please describe**

I'm not familiar with html at all, but I'd like to add a [github corner](https://tholman.com/github-corners/) on my dokka

Right now the `searchbar` is being displayed too close to the github corner, if I comment out the pulling

```
<!--            <div class="pull-right d-flex">-->
              <div id="searchBar"></div>
<!--            </div>-->
```
then it goes all the way left, after the project name, not the best but ok for the moment

**Describe the solution you'd like**

I would like a comfortable option from the gradle script to automatically add them in the html, playing it nice with the search bar

**Comment by IgnatBeresnev** [comment]
In Dokka 1.6.21 you are now able to customize generated HTML pages by providing your own `base.ftl` template. Default can be found [here](https://github.com/Kotlin/dokka/blob/1.6.21/plugins/base/src/main/resources/dokka/templates/base.ftl).

So you can add github corner next to the search bar so that it doesn't overlap:
```
    <div class="pull-right d-flex">
        <#if sourceSets??>
            <div class="filter-section" id="filter-section">
                <#list sourceSets as ss>
                    <button class="platform-tag platform-selector ${ss.platform}-like" data-active="" data-filter="${ss.filter}">${ss.name}</button>
                </#list>
            </div>
        </#if>
        <button id="theme-toggle-button"><span id="theme-toggle"></span></button>
        <div id="searchBar"></div>
    </div>
```

For more information see [documentation](https://kotlin.github.io/dokka/1.7.0-SNAPSHOT/user_guide/base-specific/frontend/#custom-html-pages).

I'll close this issue as `implemented` as having a github corner by default seems redundant :)
