### ISSUE TITLE
Dokka-CLI can't handle Boolean parameters (like -offlineMode)

### ISSUE THREAD

**Issue by solo-md** [Kotlin/dokka#1736]
**Describe the bug**
It's not possible to use `-offlineMode true` nor `-offlineMode "true"` nor `-offlineMode`. The option requires a parameter, however the boolean parameter doesn't seem to be parsed. Also the _help_ output of the error displays that the boolean parameters are not handled correctly.

**Reason**
The actual error is in kotlinx-cli library that is used by the dokka-cli. Here is the stack trace:
`
 [java]     at kotlinx.cli.ArgParser.printError(ArgParser.kt:316)
 [java]     at kotlinx.cli.ArgParser.parse(ArgParser.kt:492)
 [java]     at kotlinx.cli.ArgParser.parse(ArgParser.kt:375)
 [java]     at org.jetbrains.dokka.GlobalArguments.<init>(main.kt:90)
 [java]     at org.jetbrains.dokka.MainKt.main(main.kt:342)
`

**Expected behaviour**
It should be possible to pass "-offlineMode true" parameter to the dokka-cli as described in the documentation at https://kotlin.github.io/dokka/1.4.10/user_guide/cli/usage/

**Screenshots**
![2021-02-09_11-29-49](https://user-images.githubusercontent.com/1067208/107350871-3f210a00-6aca-11eb-8c2a-d65a865e1093.png)

**To Reproduce**
run **java -jar dokka-cli.jar <arguments>** where in the arguments pass the `-offlineMode` parameter with a value

**Installation**
- Operating system: macOS/Windows/Linux
- Build tool: Cli
- Dokka version: 1.4.20

**Comment by MarcinAman** [comment]
Hi, it turns out it was a small mistake on our site :D 

Firstly: if you want to use a boolean cli argument you should pass it as `-offlineMode` without any other `true` or `"true"`. 
Secondly: we messed up the argument positions and ended up with parameter that is named just like the description so if you are really forced to use this argument you can use it as `-Offline mode (do not download package lists from the Internet)` (+ some escaping dependent on your shell). 

I've created a small PR fixing it :)
