### ISSUE TITLE
Multi-module task should include gradle included builds

### ISSUE THREAD

**Issue by rnett** [Kotlin/dokka#1744]
**Is your feature request related to a problem? Please describe**
I have a project using gradle included builds (for compiler plugins), and I would like to be able to generate documentation for the whole project.

**Describe the solution you'd like**
The multi-module task should have an option include included builds, preferably by default.

**Comment by whyoleg** [comment]
Fixed in [Dokka 2.0.0](https://github.com/Kotlin/dokka/releases/tag/v2.0.0) in [Dokka Gradle plugin v2﻿](https://kotlinlang.org/docs/dokka-migration.html)
Example with included build can be found in [dokka/examples/gradle-v2/composite-build-example](https://github.com/Kotlin/dokka/tree/master/examples/gradle-v2/composite-build-example)
