### ISSUE TITLE
Dokka Javadoc plugin currently does not support generating documentation for multiplatform project

### ISSUE THREAD

**Issue by Albul** [Kotlin/dokka#1753]
**Question**
An older version of 1.4.0-rc is working, but new one generates this error

**Screenshots**
If applicable, add screenshots to help explain your problem

**Installation**
- Operating system: Linux
- Build tool: Gradle v6.8.2
- Dokka version: 1.4.20

**Additional context**
I need exactly javadoc, because I need to push my library to Maven Central, and javadoc is one of artifactory requirements.
```
plugins {
    ....
    id("org.jetbrains.dokka") version "1.4.10.2"
    ...
}

...
tasks {
    create<Jar>("javadocJar") {
        dependsOn(dokkaJavadoc)
        archiveClassifier.set("javadoc")
        from(dokkaJavadoc.get().outputDirectory)
    }

    dokkaJavadoc {
        dokkaSourceSets {
            named("commonMain") {
                displayName.set("common")
                platform.set(org.jetbrains.dokka.Platform.common)
            }
        }
    }
}
...
```

**Comment by kamildoleglo** [comment]
Javadoc probably won't support multiplatform projects at all, simply because it makes no sense. Javadoc presents Kotlin code as used from Java, and one can't use Kotlin/Native or Kotlin/JS from Java. Moreover, some concepts can't be translated. 

As for your issue - Javadoc is one of the requirements, but its contents are completely arbitrary. I advise you to put dokkaHtml output there or create an empty jar, as explained there: https://central.sonatype.org/pages/requirements.html

**Comment by marco-eckstein** [comment]
Of course, the Javadoc should only include documentation for the parts of the project that are usable from Java. So, it totally makes sense. I haven't checked it, but if you cannot distribute Javadoc with your code, some IDEs may not be able to display docs. IntelliJ can still use the Jar with the Kotlin sources, though.

**Comment by erksch** [comment]
Putting the output of the `dokkaHtml` task into the javadoc jar results in IntelliJ and Android Studio not displaying any documentation hints.

```kotlin
val dokkaJavadocJar by tasks.registering(Jar::class) {
    archiveClassifier.set("javadoc")
    from(tasks.dokkaHtml)
}
```

Is this really the recommended approach?

What's the recommended setup for multiplatform projects so that docs are displayed in the IDE?
It looks like Okio is using `dokkaGmf` instead of `dokkaHtml` for javadoc.
