### ISSUE TITLE
dokkaJavadoc does not recognize @return @since @author

### ISSUE THREAD

**Issue by tnfk06** [Kotlin/dokka#1770]
**Describe the bug**
dokkaJavadoc does not recognize @return, @since, @author

**Expected behaviour**
return, since , author should be generated to javadoc html file

**Screenshots**
![image](https://user-images.githubusercontent.com/77476356/110578480-44947180-81a8-11eb-9ab7-3422b977ce8a.png)

![image](https://user-images.githubusercontent.com/77476356/110578526-60981300-81a8-11eb-81fb-e0d3b39a40a3.png)

**To Reproduce**
[RoomRxJavaKotlin.zip](https://github.com/Kotlin/dokka/files/6113306/RoomRxJavaKotlin.zip)

**Dokka configuration**
Configuration of dokka used to reproduce the bug

![image](https://user-images.githubusercontent.com/77476356/110578657-a359eb00-81a8-11eb-8482-78827b55c833.png)

**Installation**
- Operating system: macOS/Windows/Linux
- Build tool: Gradle v6.7.1/Maven/Cli/3rd party plugin
- Dokka version: 1.4.20

**Additional context**
dokkaHtml works fine

![image](https://user-images.githubusercontent.com/77476356/110578999-385ce400-81a9-11eb-81a5-29ca87ab57d6.png)

**Comment by isaacchiang-kkstream** [comment]
I had the same issue in my android project with AndroidStudio. I'm using 1.6.0 version's Dokka version. Did this issue be fixed? or still working on it?

**Comment by danielshiplett** [comment]
Any idea if this is ever going to be fixed?

**Comment by IgnatBeresnev** [comment]
> Any idea if this is ever going to be fixed?

Hopefully, one day it will, but we don't have the resources to fix it now as there are more pressing issues at the moment :(

This shouldn't be awfully difficult to contribute - a convenient TODO was left in the template, indicating where it needs to be added: https://github.com/Kotlin/dokka/blob/1.7.20/plugins/javadoc/src/main/resources/views/class.korte#L284

How Javadoc plugin and its templating works in beyond me, but implementing return/since/author it similar to how `parameters` property is handled should work, see [JavadocContentToTemplateMapTranslator](https://github.com/Kotlin/dokka/blob/d61df34a784ab2f05d0facf0acad557b7743cf10/plugins/javadoc/src/main/kotlin/org/jetbrains/dokka/javadoc/renderer/JavadocContentToTemplateMapTranslator.kt#L120).

For anyone wishing to contribute this fix, [Developer Guides](https://kotlin.github.io/dokka/1.7.20/developer_guide/introduction/) can help you get started.

**Comment by turovaia** [comment]
Hello! I'd like to approach the issue. Is it still actual?

**Comment by IgnatBeresnev** [comment]
@turovaia I believe it is, yes! If you feel stuck or need pointers, feel free to ask questions here or in the `#dokka` channel in [Kotlin Community Slack](https://surveys.jetbrains.com/s3/kotlin-slack-sign-up)

**Comment by IgnatBeresnev** [comment]
The fix will be released in 1.9.0
