### ISSUE TITLE
HTML search and sidebar server requirement

### ISSUE THREAD

**Issue by DanielRibeiroMaciel-TomTom** [Kotlin/dokka#1897]
Hi!

We're wondering if it is possible to not have this webserver requirement for using search and sidebar? What is the technical limitation for it?
It is important for us to be able to distribute the docs in standalone offline form (zipfile with html).

Kind regards,
Daniel

**Comment by MarcinAman** [comment]
Hi, for now it is required to have a http sever since we are fetching js files using fetch API. In the nearest future we would like to alleviate this: https://github.com/Kotlin/dokka/issues/1795

For now i recommend either attaching a small python script that would host the docs or using the webserver build into Intellij (or any other Jetbrains IDE you use)

**Comment by DanielRibeiroMaciel-TomTom** [comment]
Thanks @MarcinAman
