### ISSUE TITLE
Side bar does not appear when deploying to GitHub pages

### ISSUE THREAD

**Issue by BomBardyGamer** [Kotlin/dokka#1901]
**Describe the bug**
The side bar does not appear for GitHub pages deployments

**Expected behaviour**
When deployed to GitHub pages, the side bar shows up fine with no issues

**Screenshots**
https://i.imgur.com/RGJRWlP.png

**To Reproduce**
Deploy https://github.com/KryptonMC/kdocs to GitHub pages and browse it

**Dokka configuration**
N/A (I don't think, since I think I know what the issue is)

**Installation**
- Operating system: N/A
- Build tool: Gradle (N/A though)
- Dokka version: 1.4.20 (also N/A)

**Additional context**
I am fully aware of issues when there is no web server (namely, #1795 ), but I thought that GitHub pages was an adequate web server for this purpose, hence why I am confused at this error.

**Are you willing to provide a PR?**
I would, but I think this is already on the wish list for 1.5

**Comment by kamildoleglo** [comment]
Strange, it looks like the JS and JSON files are loaded correctly, not sure why it's not showing then. I'll investigate that

**Comment by MarcinAman** [comment]
Hi, would you mind rerendering your documentation? To be fair i dont know what is the issue since i've tried deploying my own copy of your library and it works: https://marcinaman.github.io/Krypton/

Also,  since you have a lot of API surface the loading times may not be the fastest but this will be improved by: https://github.com/Kotlin/dokka/issues/1855
