### ISSUE TITLE
Create multi module custom task

### ISSUE THREAD

**Issue by leandroBorgesFerreira** [Kotlin/dokka#1957]
**Question**
Similar question to issue: #1947

I only see in the documentation the possibility do create a custom task for a single module:
```
val customDokkaTask by creating(DokkaTask::class) {
    dependencies {
        plugins("org.jetbrains.dokka:kotlin-as-java-plugin:1.4.32")
    }
}
```

Which in Groovy translate closely to this: 
```
tasks.register('dokkaDokkasaurus', DokkaTask) {
    dependencies {
        dokkaPlugin(Dependencies.dokkasaurus)
    }

    outputDirectory = file("../build/dokka/docusaurus/stream-chat-android-client")
}
```

The problem is that I have a multimodule project and if I apply Dokka in each module I lose links for classes of other modules, which is a real show stopper =|. 

All formats have their `Partial` version and the multi-module version. How can I achieve this? Or... where is the code can I have an idea of how to do this?

**Comment by MarcinAman** [comment]
Hi, 
1) You should configure `DokkaMultiModuleTask::class` not `DokkaTask::class` since the second one is only for the single module tasks (thats why you lose links)
2) If you want to configure the plugin i'd do it in the `DokkaTaskPartial` not in multimodule, since they don't propagate. You can use all projects block in gradle or equivalent. The idea behind it is that you have a root multimodule task that just calls partials and gathers their outputs into 1 with some processing.

Here is a basic example of a multimodule project to help you: https://github.com/Kotlin/kotlin-examples/blob/25040fe92994ab46ebac6a6450d3ad1d3e870af1/gradle/dokka/dokka-multimodule-example/parentProject/childProjectB/build.gradle.kts#L12

**Comment by leandroBorgesFerreira** [comment]
If someone is reading this in the future: 
You can also configure it like this ->
1. Add your plugin to your module in the partial tasks
```
tasks.register("[some_task]Partial", DokkaTaskPartial) {
    dependencies {
        dokkaPlugin("some:plugin:1.0.0")
    }
}
```

2. Create a multi module task that calls all the partial tasks:
```
tasks.register("[some_tasks]MultiModule", DokkaMultiModuleTask) {
    dependencies {
        dokkaPlugin("some:task:[some_task]-template-processing:1.0.0")
    }

    addSubprojectChildTasks("[some_task]Partial1")
    addSubprojectChildTasks("[some_task]Partial2")
    addSubprojectChildTasks("[some_task]Partial3")
}
```

The documentation will be merged into one final output and links between modules will be generated. 

There's the need to configure the template processing, but then it will be ok. You can just copy from the Gfm plugin and create your own custom one.
