### ISSUE TITLE
I get "Nothing to document" when running Dokka in pure Java project

### ISSUE THREAD

**Issue by andrews-moc** [Kotlin/dokka#2421]
**Question**
What could be the reason of getting "Exiting Generation: Nothing to document"?

**Screenshots**
If applicable, add screenshots to help explain your problem

**Installation**
- Operating system: macOS
- Build tool: Gradle v7.2
- Dokka version: 1.6.0

**Additional context**
We are setting up like it's described [here](https://kotlin.github.io/dokka/1.6.0/user_guide/gradle/usage/) (preferred way).
Project is build successfully.
Although when we run for example dokkaJavadocPartial Gradle task, we receive
```
> Task :androidSdk:dokkaJavadocPartial
Initializing plugins
Dokka is performing: documentation for androidSdk
Validity check
Creating documentation models
Exiting Generation: Nothing to document
```

Tried on several pure Java projects - the same issue on both.

Project structure is:
```
-| android-project (root)
-------| android-project
-------------| src
-------------------| main
```

Please help us understand the reason what's wrong. Thank you.

**Comment by IgnatBeresnev** [comment]
Hi! Dokka is a kotlin-first project, so it doesn't seem to work without Kotlin plugin applied.

You can try [adding](https://developer.android.com/kotlin/add-kotlin) kotlin plugin to your project. I assume you are using **groovy**-based build scripts, so it'll be something like this.

```
buildscript {
    dependencies {
        classpath("org.jetbrains.dokka:dokka-gradle-plugin:1.6.10")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10")
    }
}

apply plugin: 'org.jetbrains.dokka'
apply plugin: 'kotlin'
```

Also, you might want to add `kotlin-as-java` plugin in order to see signatures as Java code.

Please note that java support in dokka is not ideal, you might encounter issues or inaccuracies when it comes to documentation or signatures. However, we're glad that you want to try Dokka out and would appreciate it if you'd tell us about any bugs you might encounter :)
