### ISSUE TITLE
Private Java field with public accessors has private keyword in Kotlin signature

### ISSUE THREAD

**Issue by flyingfish162** [Kotlin/dokka#2439]
**Describe the bug**
I have a module mixed with java/kotlin classes in Android project. Generating docs with includeNonPublic set to false still adds Java non-public properties (that have public getter/setter specifically) to the output while their getter and setter not outputted.

**Expected behaviour**
Non-public properties not visible in the html output while their public getter and setter are visible.

**Screenshots**
Current generated doc page:
<img width="1190" alt="Screen Shot 2022-04-14 at 17 27 55" src="https://user-images.githubusercontent.com/56924323/163356927-e1e4f725-e3c0-44de-9bce-4ea269ea6ea7.png">
<img width="1211" alt="Screen Shot 2022-04-14 at 17 30 22" src="https://user-images.githubusercontent.com/56924323/163356938-5fe906df-e00b-4a46-8a13-764f47b11515.png">

**To Reproduce**
1. Create TestClass.java:

```Java
package com.example.test;

public class TestClass {
    private int a;
    int b;

    public int getA() {
        return a;
    }

    public void setA(int a) {
        this.a = a;
    }

    public int getB() {
        return b;
    }

    public void setB(int b) {
        this.b = b;
    }
}
```

2. Run ./gradlew app:dokkaHtml
3. Output should not contain a and b but public getter and setter

**Dokka configuration**
Configuration of dokka used to reproduce the bug

Module build.gradle:
```Gradle
plugins {
    id 'com.android.application'
    id 'kotlin-android'
}

apply from: 'kdoc.gradle'
```

kdoc.gradle:
```Gradle
apply plugin: "org.jetbrains.dokka"

dokkaHtml {
    outputDirectory.set(file("build/kdoc"))
    dokkaSourceSets {
        configureEach {
            includeNonPublic.set(false)
            skipEmptyPackages.set(true)
            jdkVersion.set(8)
            noAndroidSdkLink.set(true)
            noStdlibLink.set(true)
            noJdkLink.set(true)
        }
    }
}
```

Project build.gradle:
```Gradle
buildscript {
    dependencies {
        classpath 'com.android.tools.build:gradle:7.1.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.20"
        classpath("org.jetbrains.dokka:dokka-gradle-plugin:1.6.10")
    }
}
```

**Installation**
- Operating system: macOS
- Build tool: Gradle v7.2
- Dokka version: 1.6.10

**Additional context**
I see this issue since Dokka version 1.4.32

**Comment by IgnatBeresnev** [comment]
Hi! 

I believe this is how kotlin-java interop works:
* From Kotlin's perspective, if a `java` property has both a getter and a setter - it's a `var` property. If it only has the getter, it's a `val`.
* From Java's perspective, if the kotlin property is `var`, it contains both the getter and the setter, while a `val` only contains the getter.

![2022-04-25_23-48-59](https://user-images.githubusercontent.com/22685910/165172415-fb6ecc98-0a2b-4b41-be33-91f545e3e2b4.png)

> Non-public properties not visible in the html output while their public getter and setter are visible.

So I don't think your expected behaviour is correct, it would simply be wrong even compared to the Intellij IDEA.

However, it is indeed wrong that the word `private` is present in there. It should not be there, then everything will make sense and be correct.

**Comment by IgnatBeresnev** [comment]
For anyone looking to fix this, here's the expected behaviour. For the java class
```java
public class TestClass {
    private int a;

    public int getA() {
        return a;
    }

    public void setA(int a) {

    }
}
```

it should generate the following signature:
![2022-04-26_00-14-24](https://user-images.githubusercontent.com/22685910/165175905-4bfa664d-3bfb-4cb7-917b-a380110255b8.png)


It seems to be a relatively easy fix for in terms of writing code, here's where the problem is: [KotlinSignatureProvider#propertySignature](https://github.com/Kotlin/dokka/blob/c44bf5487bd32f90a4576859548f1db0e9355a07/plugins/base/src/main/kotlin/signatures/KotlinSignatureProvider.kt#L239).

It should throw away `private` (and possibly other non-public) visibility keyword if this property has publicly available accessors. For instance - private properties with public getters and setters, like in the example above.

The fix should be roughly something like this (should be cleaned up of course):
```kotlin
p.visibility[sourceSet].takeIf {
    val isPrivateJavaPropertyWithPublicAccessors =
        (it == JavaVisibility.Private)
                && (p.getter?.visibility?.get(sourceSet) == JavaVisibility.Public)
                && (p.setter?.visibility?.get(sourceSet) == JavaVisibility.Public)

    it !in ignoredVisibilities && !isPrivateJavaPropertyWithPublicAccessors
}?.name?.let { keyword("$it ") }
```

However, fixing this will involve some thinking and testing for corner cases:
1. Can setting `documentedVisibilities` (and legacy `includeNonPublic`) introduce more bugs after the fix?
2. What to do with other modifiers, such as protected/package-private.
3. What to do if accessors are not public, or only one accessor is public and the other is private. This should probably be compared to how Intellij IDEA behaves.
4. Do we need to take into account the value set in `documentedVisibilities`?

And more tests with corner cases will need to be added. `SignatureTest` is for Kotlin sources only, so a class nearby, something like `JavaToKotlinSignatureTest` would do the job.

**Comment by EvgeniyMish** [comment]
Hi! I still experience this issue in 1.8.20.

**Comment by IgnatBeresnev** [comment]
@EvgeniyMish could you please share the use case? A number of unit tests were written in #2439, so it's unlikely to be a regression - most likely it's a different bug or yet another corner case
