### ISSUE TITLE
Documentation output styles

### ISSUE THREAD

**Issue by hastebrot** [Kotlin/dokka#25]
There are so many different styles for API documentation for JVM languages. Since Kotlin aims to integrate tight to Java it would be nice to be able to output Kotlin documentation in a similar style to Java 6, 7, or 8. Or even Android for Android-specific projects.

Here a short list of different styles for API docs:

- Java 6: http://docs.oracle.com/javase/6/docs/api/
- Java 7: http://docs.oracle.com/javase/7/docs/api/
- Java 8: http://docs.oracle.com/javase/8/docs/api/
- Groovy 2.2: http://docs.groovy-lang.org/2.2.0/html/gapi/
- Groovy 2.4: http://docs.groovy-lang.org/2.4.0/html/gapi/
- Android: http://developer.android.com/reference/packages.html
- Scala: http://www.scala-lang.org/api/current/
- Clojure: http://clojure.github.io/clojure/branch-clojure-1.6.0/index.html

**Comment by yole** [comment]
Dokka now supports the 'javadoc' output format, which uses the actual javadoc tool from Java 8 to generate output pages, so that the output is fully compatible with tools that parse Javadoc HTML. We don't see any benefit in being compatible with other API documentation styles, and don't plan to work on that, but we will consider accepting external contributions if someone from the community is willing to work on that.
