### ISSUE TITLE
Make the member name column in HTML flexible for long names

### ISSUE THREAD

**Issue by mahozad** [Kotlin/dokka#2516]
Created this issue as was suggested in #2513.

The problem is obvious in this screenshot:

![Screenshot showing the problem](https://user-images.githubusercontent.com/29678011/170542564-cd8014c6-a6c8-4df8-a469-0e17070183c8.png)

**Installation**
- Operating system: Windows
- Build tool: Gradle v7.4.2
- Dokka version: 1.6.21

**Are you willing to provide a PR?**
Sorry, I may not be able to provide one for this issue.

**Comment by IgnatBeresnev** [comment]
The issue has been addressed in #2836, and it will be released in Dokka 1.9.0.

We've also investigated the ability to remove the left column altogether so that there's no problem to begin with, but it proved to be more difficult than we expected, so we'll have to postpone the idea for now.

What it's going to look like for the time being:

![2023-05-30_22-55-47](https://github.com/Kotlin/dokka/assets/22685910/6653c8d5-ef78-4e74-a3e2-266bff9e20bf)
