### ISSUE TITLE
Reporting value of constants defined in Java

### ISSUE THREAD

**Issue by juliamcclellan** [Kotlin/dokka#2524]
**Describe the bug**
#1489 made it so the `DProperty` generated for a primitive constant defined in Kotlin contains a `DefaultValue` with the value of that constant. However, a `DProperty` generated for a Java constant (e.g. `public static final int FOO = 5;`) does not have a `DefaultValue`, so there isn't a way to access the value of the constant.

The change [specifically used `KotlinSourceElement`](https://github.com/Kotlin/dokka/blob/2e4121457a0fbae1a216007aee6c84a01be628f5/plugins/base/src/main/kotlin/translators/descriptors/DefaultDescriptorToDocumentableTranslator.kt#L1115). Is it possible to change this so it will work with Java as well?

**Installation**
- Operating system: macOS
- Build tool: Gradle v7.3
- Dokka version: 1.6.20-dev-154

**Comment by IgnatBeresnev** [comment]
JFYI the "bug" was not because `KotlinSourceElement` was used in `DefaultDescriptorToDocumentableTranslator`

We currently have two translators:
* `DefaultDescriptorToDocumentableTranslator` is invoked only for `Kotlin` sources
* `DefaultPsiToDocumentableTranslator` is invoked only for `Java` sources

Parsing `Java` constant values just wasn't implemented in `DefaultPsiToDocumentableTranslator`, but it was easy enough to implement
