### ISSUE TITLE
Inconsistency in visibility of protected properties

### ISSUE THREAD

**Issue by atyrin** [Kotlin/dokka#2536]
Let's have a code like:

```java
public class JavaClsWithProperties {
    protected int protectedProperty = 0;
    private int protectedGetterAndProtectedSetter = 0;

    protected int getProtectedGetterAndProtectedSetter() {
        return protectedGetterAndProtectedSetter;
    }

    protected void setProtectedGetterAndProtectedSetter(int protectedGetterAndProtectedSetter) {
        this.protectedGetterAndProtectedSetter = protectedGetterAndProtectedSetter;
    }
}
```
and inheritor
```kt
open class InheritJavaClsProperties: JavaClsWithProperties(){
    protected val protectedX: Int = 0
}
```

What we see in generated documentation with default `documentedVisibilities` (Public API only):
For Java property with protected getter/setter is shown
<img width="755" alt="image" src="https://user-images.githubusercontent.com/7689049/174025327-8c5323a0-6725-4cc4-a185-3538b44e297f.png">
For inheritor in Kotlin both properties are shown
<img width="791" alt="image" src="https://user-images.githubusercontent.com/7689049/174025523-bed1cb98-199a-4877-b8b5-38999a261e5d.png">

**Expected behaviour**
My expectation is that all protected properties are hidden. But probably for an open class, they might be shown with the visibility modifier.

**Installation**
- Dokka version: 1.7.0
- Kotlin: 1.7.0

**Comment by IgnatBeresnev** [comment]
These are actually two separate bugs:
1. Incorrect mapping of Java's `Protected` visibility, it resolved to Kotlin's `Public`. Fixed it, now `Java.Protected` -> `Kotlin.Protected`
2. non-public-api fields with accessors that are public api were hardcoded to be `Kotlin.Public`, that was a mistake. Made it so that property visibility is inherited from getter's visibility. So for a field with a protected getter it will generate a protected kotlin property
