### ISSUE TITLE
Public Java property is shown as `val`

### ISSUE THREAD

**Issue by atyrin** [Kotlin/dokka#2539]
For public properties without getter or setter Dokka shows keyword `val` instead of `var`

```java
public class JavaClass {
    public int publicProperty;
}
```

<img width="567" alt="image" src="https://user-images.githubusercontent.com/7689049/174113408-0347616e-ca34-47da-a27d-e0e34199e508.png">

**Installation**
- Dokka version: 1.7.0-dev-170

**Comment by IgnatBeresnev** [comment]
Yeah, turns out it's not as easy to fix :(

Adding this will solve it for java classes
```kotlin
private fun DProperty.isMutable(sourceSet: DokkaSourceSet): Boolean {
    return when(this.documentableLanguage(sourceSet)) {
        DocumentableLanguage.KOTLIN -> this.setter != null
        DocumentableLanguage.JAVA -> {
            // java properties without getters and setters should be `var`
            if (this.getter == null && this.setter == null) true else this.setter != null
        }
    }
}


if (p.isMutable(sourceSet)) keyword("var ") else keyword("val ")
```

But `Kotlin` inheriting `Java` will result in `sourceLanguage == Kotlin`, and it will be `val`.

We would need a way to see from which language this property came from, and if it came from Java - apply this special rule
