### ISSUE TITLE
Why does `dokka` introduce classes?

### ISSUE THREAD

**Issue by Pamplemousse** [Kotlin/dokka#2582]
**Question**

Why does `dokka` mention "classes" while none are declared in the code?

**Description**

```bash
$ tree src/
src
└── main
    └── kotlin
        └── hello.kt
        
$ cat src/main/kotlin/hello.kt
package com.foo.politeness

/**
 * Says "hello".
 *
 * @param name The name of the person to say "hello" to.
 * @return The message saying "hello".
 */
fun hello(name: String) : String {
  return "Hello ${name}!"
}

$ mvn dokka:dokka
```

And the result I get shows:

![Screenshot from 2022-07-22 15-25-23](https://user-images.githubusercontent.com/2647236/180448644-3e71cda6-8ea5-4967-8538-157a67297b86.png)

**Installation**
- Operating system: Linux
- Build tool: Maven
- Dokka version: 1.7.10

**Comment by IgnatBeresnev** [comment]
Hi! You've applied `kotlin-as-java-plugin`, which generates documentation as if you're observing this code from Java's perspective.

Java doesn't have the concept of package-level function like Kotlin, it's illegal. However, because you can call Kotlin code from Java code, this function needs to be accessible somehow.

Try calling your Kotlin function from a Java class, you'll see that a class has been generated by the compiler to hold the function.

Kotlin file
```kotlin
package me.beresnev.dokka.debug

/**
 * Says "hello".
 *
 * @param name The name of the person to say "hello" to.
 * @return The message saying "hello".
 */
fun hello(name: String) : String {
    return "Hello ${name}!"
}
```

Java file
```java
package me.beresnev.dokka.debug;

public class JavaClass {
    void foo() {
        KotlinClassKt.hello("world"); // compiles just fine
    }
}
```

**Comment by Pamplemousse** [comment]
> You've applied kotlin-as-java-plugin, which generates documentation as if you're observing this code from Java's perspective.

Aaaah, thanks for pointing that out!

I didn't realise that I could "skip" the `<dokkaPlugins>` part of the configuration... :facepalm:
All better now :slightly_smiling_face:
