### ISSUE TITLE
processFunction of DocumentableReplacerTransformer is not open

### ISSUE THREAD

**Issue by nk-coding** [Kotlin/dokka#2654]
**Describe the bug**
The `processFunction` function of [DocumentableReplacerTransformer](https://github.com/Kotlin/dokka/blob/master/plugins/base/src/main/kotlin/transformers/documentables/DocumentableReplacerTransformer.kt) is in contrast to all other `process...` functions not `open` and can therefore not be overwritten.

**Expected behaviour**
Mark the `processFunction` function as `open`

**Are you willing to provide a PR?**
Yes, sure

**Comment by IgnatBeresnev** [comment]
Hi! Indeed, it looks like it should be open like all the other functions in the class

Do you wish to contribute this change? It would involve changing the signature and running `./gradlew apiDump` to re-generate API files for [binary compatibility validator](https://github.com/Kotlin/binary-compatibility-validator)

Otherwise I can fix it quickly
