### ISSUE TITLE
Possible to generate multi module projects using the CLI?

### ISSUE THREAD

**Issue by rohan-mehta** [Kotlin/dokka#2770]
**Question**
I'm following the [Command Line guide](https://kotlin.github.io/dokka/1.7.20/user_guide/applying/cli/) to create docs. The docs are a bit out of date, but I was able to get it working. However, I'm not totally sure how I might use it to generate multi module docs. Are there any examples I can follow? 

**Installation**
- Operating system: macOS
- Build tool: CLI
- Dokka version: 1.7.20

**Comment by IgnatBeresnev** [comment]
It should be possible, although not quite straightforward and easy. Frankly I've neither done it, nor heard of anyone succeeding, nor would I recommend doing it :sweat_smile: 

Is there any reason you want to use the CLI runner for this as opposed to using the Gradle plugin? Maybe we could spend less time on resolving the blocker? 

____

If you're determined to use the CLI runner, here's my thoughts:

We've re-written documentation in #2728, it's not out yet, but you can see the preview for the CLI runner [here](https://ignatberesnev.github.io/static/dokka/docs/kotlinlang/cli.html), it should help you with configuration and understanding what's going out. Note that some configuration properties I'm going to mention are not covered in the documentation as this use case should be quite rare.

You can read how `*MultiModule` and `*Partial` tasks work for the Gradle plugin [here](https://ignatberesnev.github.io/static/dokka/docs/kotlinlang/gradle.html#multimodule-tasks). You'll have to do something similar, but manually.

First, Partial tasks are run for each module separately, and then the parent MultiModule task is run, which processes output from all partial tasks and produces ready-to-use documentation. Partial tasks are run with [DokkaConfiguration#delayTemplateSubstitution](https://github.com/Kotlin/dokka/blob/d61df34a784ab2f05d0facf0acad557b7743cf10/core/src/main/kotlin/configuration.kt#L132) set to `true` - this leaves template resolution to the MultiModule task so that cross-module references, navigation links and everything else can be linked correctly (since it knows about all modules).

So it looks like you'd have to have separate JSON configurations for each module (with `delayTemplateSubstitution`), similar to how [DokkaTaskPartial](https://github.com/Kotlin/dokka/blob/1.7.20/runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/DokkaTaskPartial.kt) is created for each subproject.

Then you'd need a separate JSON configuration for the MultiModule run. You'd probably have to supply [templating-plugin](https://mvnrepository.com/artifact/org.jetbrains.dokka/templating-plugin) and [all-module-page-plugin](https://mvnrepository.com/artifact/org.jetbrains.dokka/all-modules-page-plugin) to `pluginsClasspath`, and maybe some additional libraries, you'll figure it out by resolving `ClassNotFound` errors :) The plugins should get bootstrapped automatically.

For the MultiModule run only, it looks like you'll have to configure [DokkConfiguration#module](https://github.com/Kotlin/dokka/blob/d61df34a784ab2f05d0facf0acad557b7743cf10/core/src/main/kotlin/configuration.kt#L129) property and provide locations of the modules.

CLI runner's JSON configuration is deserialized as `DokkaConfiguration`, so the mapping of fields is 1:1, it should be easy enough to understand which names and values to set.

With all of that done, it should either work as expected or you should be close.

You can look at the Gradle plugin, its tasks and configuration for examples, although that's also not as easy to extract information from it. You can use `DokkaConfiguration.toJsonString()` extension to dump existing configuration as JSON, but there's no way to get configuration of a task from the buildscript, so you'll have to stop in debugger to use it, probably somewhere in `SingleModuleGeneration` or `AllModulesPageGeneration` (they have access to configuration through `context.configuration`). But that could be the easiest solution, actually - add the gradle plugin to your project, let it auto-configure all tasks (and  thus configurations), and then just dump configurations as JSONs that you'll be able to use from the CLI runner.

**Comment by rohan-mehta** [comment]
Thanks for the reply @IgnatBeresnev. Your suggestion worked. The one slight gotcha for me, was that the `MultiModule` run silently did nothing if I didn't pass the templating-plugin and all-module-page-plugin. Once I passed those, it successfully generated things correctly. Thanks a ton for helping me so quickly!

**Comment by IgnatBeresnev** [comment]
I'm glad it worked :+1: 

Could you please describe your use case for the CLI runner? Why not use the Gradle plugin?

We'd like to know more why people use it so that we can either improve the CLI runner itself or resolve problems in the Gradle plugin that stop people from using it.

**Comment by rohan-mehta** [comment]
Oh, my project doesn’t use gradle as the build system. The CLI runner is really useful if you have a different build system eg CMake, bazel, buck, so would be great if you kept investing in it :)
