### ISSUE TITLE
How to save table of content after excluding html dirrectory from project dirrectory?

### ISSUE THREAD

**Issue by Novikov** [Kotlin/dokka#2788]
**Question**
I use dokka to generate documentation for my android project. After completing the gradle task, a directory with documentation is created in the build folder, in which there is a table of contents by sections. Opened with a browser through the index.html file. The point is that I need to keep the documentation separate from the code. I take the entire folder and put it in a zip archive. After extracting the folder with the dock from the android folder, the table of contents is lost. Is it possible to save it somehow?

**Screenshots**
![11](https://user-images.githubusercontent.com/49527849/209098244-8e1f27b1-24c8-4949-9026-d796681dec88.png)
![12](https://user-images.githubusercontent.com/49527849/209098261-bc893d61-37ff-49ee-9163-d08ed665bd32.png)

**Installation**
- Operating system: macOS
- Build tool: Gradle v7.0.4
- Dokka version: 1.7.10

**Comment by IgnatBeresnev** [comment]
Unfortunately, it's a current limitation of the format that the generated HTML pages need to be hosted on a web server in order to be rendered correctly, and that includes the navigation menu.

You can use nginx or any free static site hosting service, such as [GitHub Pages](https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages).

Locally, you can use the [built-in IntelliJ web server](https://www.jetbrains.com/help/idea/php-built-in-web-server.html). that comes with IntelliJ Ultimate.

I'll close this issue as it's a known limitation, but feel free to follow #1795 for updates.
