### ISSUE TITLE
Version drop down is broken

### ISSUE THREAD

**Issue by ansman** [Kotlin/dokka#2920]
**Describe the bug**
My project uses multimodule dokka paired with versioning plugin to make permanent version docs. This appears to work fine but when I go in to the docs for a specific module the 

**Expected behaviour**
I expect the drop down to select which version to work when navigating older docs.

**Screenshots**
<img width="307" alt="image" src="https://user-images.githubusercontent.com/102883/224813867-caf3269e-f979-443c-8a37-6a9085889af9.png">

**To Reproduce**
You can see the issue in action here: https://auto-dagger.ansman.se/dokka/android/testing/index.html

The relevant setup code is here: https://github.com/ansman/auto-dagger/blob/main/build.gradle.kts#L112-L128

**Dokka configuration**
```Kotlin
val versionCurrentDocs by tasks.registering(DokkaMultiModuleTask::class) {
    enabled = !isSnapshotVersion
    outputDirectory.set(olderVersionsFolder.resolve(version))
    pluginConfiguration<VersioningPlugin, VersioningConfiguration> {
        version = providers.gradleProperty("version").get()
    }
    addChildTasks(dokkaProjects, "dokkaHtmlPartial")
}

tasks.dokkaHtmlMultiModule {
    removeChildTasks(subprojects - dokkaProjects)
    pluginConfiguration<VersioningPlugin, VersioningConfiguration> {
        version = providers.gradleProperty("version").get()
        olderVersionsDir = olderVersionsFolder
    }
}
```

**Installation**
- Operating system: macOS
- Build tool: Gradle v7.6.1
- Dokka version: 1.7.20

**Additional context**
Could this be caused by me using `dokkaHtmlPartial` do version the old docs perhaps?

**Are you willing to provide a PR?**
Yes

**Comment by IgnatBeresnev** [comment]
This is indeed most likely due to improper configuration. With multi-project builds it might be tricky to configure. 

Judging by the [ktor configuration](https://github.com/ktorio/ktor/blob/main/build.gradle.kts#L147) for the versioning plugin, it looks like you need to apply the plugin in the documented subprojects, and then configure the multimodule task. There should be no need for adding tasks manually, it should be configured automatically.

Try doing something similar to ktor, it should work
