### ISSUE TITLE
Can I give order to multiple Markdown files?

### ISSUE THREAD

**Issue by eunwoo-park-nhn** [Kotlin/dokka#2999]
**Question**
During the build of DokkaHtmlMultiModule task,
I have multiple Markdown (.md) files, Dokka combining them into a single file when I write like this.
```
tasks.dokkaHtmlMultiModule {
    moduleName.set("Dokka test")
    includes.from("README.md", "DeprecatedAPIs.md")
}
```
However, I'm wondering is there a way to give order to these documents?

**Installation**
- Operating system: macOS
- Build tool: dokka-gradle-plugin
- Dokka version: 1.8.10

**Comment by IgnatBeresnev** [comment]
Hi! I'm not sure what exactly mean or want to achieve by ordering the markdown documents.. 

Could you describe your use case? What's the content of the files, what is Dokka generating and how would you like to see it instead?

**Comment by eunwoo-park-nhn** [comment]
Hello, 

When I write below, then Dokka combiles 2 markdown pages and creates a single page for intro.
```
tasks.dokkaHtmlMultiModule {
    includes.from("README.md", "DeprecatedAPIs.md") 
}
```


However, the current behavior is DeprecatedAPIs.md's content displayed first, followed by the content of README.md.
But what I want is, for the contents of README.md to appear first, followed by the content of DeprecatedAPIs.md.

I would like the content to be merged in the order I specified in includes.from().

**Comment by IgnatBeresnev** [comment]
Could you please provide the contents of those files so that I can replicate it locally, or make a reproducer project / screenshots?

I don't think the order is defined by the order of the files at all, the content is most likely sorted alphabetically by the names of the modules/packages, but there might be something I'm missing or I'm not aware of.

**Comment by eunwoop** [comment]
@IgnatBeresnev 
It seems content is sorted by hash values because it's Set.
I made a simple PR for this. Could you please review this?
I replace Set to LinkedHashSet for keep order what specified in includes.from().

**Comment by eunwoop** [comment]
The files I sent you do not contain # Module or # Package headers because they are not for child modules, 
they are for top level first intro page. So they don't produce any exceptions in my environment. Did you set files for top level for tasks.dokkaHtmlMultiModule's include?
And I will share my screenshot.

Anyway I don't mean current state is problem, I just want if there is feature for ordering markdown files for intro(first) page for dokkaHtmlMultiModule. and I want to make this change with my PR

> What I want is when I write like this
```
includes.from("README.md", "DeprecatedAPIs.md") 
```
* README.md -> DeprecatedApis.md 
<img width="1008" alt="image" src="https://github.com/Kotlin/dokka/assets/5337275/799ee544-402d-4bd4-a996-12b2bc25cfd8">

* But current state is : DeprecatedApis.md -> README.md
![image](https://github.com/Kotlin/dokka/assets/5337275/d1f78a6e-512a-4bb1-9955-8730c0a05dd0)

Thank you for read this!!!

**Comment by IgnatBeresnev** [comment]
Oh, I got it! So it works only for the `DokkaHtmlMultiModule` task in multi-module projects. Doing the same thing in a single-module project would lead to the errors I posted above.

I'm actually not sure if this is a bug or a feature, we'll have to discuss it. And if it's a feature, we need to figure out how it's going to be configured in the new Gradle plugin, because there will be no distinction between `MultiModule` and `Partial` tasks. 

I'll add the `configuration` tag and leave the question open until we figure it out, if you don't mind
