### ISSUE TITLE
Custom module name leads to hidden packages for maven runner

### ISSUE THREAD

**Issue by atyrin** [Kotlin/dokka#3011]
Configure the Dokka Maven plugin with custom module name:
```xml
<plugin>
                <groupId>org.jetbrains.dokka</groupId>
                <artifactId>dokka-maven-plugin</artifactId>
                <version>1.8.10</version>
<!--                <version>1.7.20</version>-->
                <executions>
                    <execution>
                        <phase>pre-site</phase>
                        <goals>
                            <goal>dokka</goal>
                        </goals>
                    </execution>
                </executions>

                <configuration>
                    <moduleName>Dokka Maven Project</moduleName>
                </configuration>
            </plugin>
```

As a result, rendered documentation will filter out all sources:
<img width="1205" alt="image" src="https://github.com/Kotlin/dokka/assets/7689049/ad2c75bf-43f3-46bb-9d7e-ad173a0f7732">

The issue appeared in `1.8.10`. For `1.7.20`, it works fine. Also, it does not reproduce for Gradle runner.

**Comment by atyrin** [comment]
As I see in Gradle filters has the original module name
<img width="613" alt="image" src="https://github.com/Kotlin/dokka/assets/7689049/d9b5638f-7082-43d2-bdae-b88834e7b72f">

In Maven, it is replaced by the new name
<img width="643" alt="image" src="https://github.com/Kotlin/dokka/assets/7689049/e1ff9ddc-9093-42c3-8934-6161523cb1a7">

**Comment by IgnatBeresnev** [comment]
This happens only for Maven module names that contain a space. The CLI runner is also affected.

### Bug explanation

In the Maven runner, the `moduleName` property is set as `DokkaSourceSetID#scopeId`, so in the case above it'll be `Dokka Maven Project`. In the Gradle runner it is [set to the task path](https://github.com/Kotlin/dokka/blob/fcb2f4ae72bdc62df37e61360d2d206c36717612/runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/dokkaSourceSetIDFactory.kt#L8), so in the simplest case it'll be just `dokkaHtml`.

Note: `DokkaSourceSetID` [defines](https://github.com/Kotlin/dokka/blob/fcb2f4ae72bdc62df37e61360d2d206c36717612/core/src/main/kotlin/configuration.kt#L88) `toString()` as
```kotlin
override fun toString(): String {
    return "$scopeId/$sourceSetName"
}
```

Then there's this code. If a table entry belongs to multiple source sets, this code sets multiple space separated values for `data-filterable-set` - this can be seen on the screenshot above.

https://github.com/Kotlin/dokka/blob/21afcb40ad5265d2214c05179614eb2f070526f2/plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt#L571-L576

When everything is rendered, the following JS code splits these values by space, and then checks whether they are among the active filters:

https://github.com/Kotlin/dokka/blob/f55e22d5fe3f9121b7ed81d0c3f8c6a094dff45c/plugins/base/src/main/resources/dokka/scripts/platform-content-handler.js#L325-L326

So if `moduleName` is set to `Dokka Maven Project`, its `DokkaSourceSetID.toString()` will be `Dokka Maven Project/JVM` - this value will be set for `activeFilters`. 

However, when the actual filtering happens, in the JS code it'll be split as `[Dokka, Maven, Project]` instead of a single entry.

This leads to the table entry being hidden, as if the filter for it is not currently active.
