### ISSUE TITLE
[K2] Migrate to new Standalone Analysis API

### ISSUE THREAD

**Issue by vmishenev** [Kotlin/dokka#3114]
This issue is a requirement for 
* #3140

___

It depends on [KT-60884](https://youtrack.jetbrains.com/issue/KT-60884/Analysis-API-Improve-standalone-mode-project-model-creation)
The current Standalone API is a prototype. It doesn't allow to migrate to compiler 1.9.20 due to the impossibility of creating `GlobalSearchScope` ([contentScope](https://github.com/JetBrains/kotlin/blob/2b5f839fac52c54a36bbd2688e1c80bd4f63a0f0/analysis/project-structure/src/org/jetbrains/kotlin/analysis/project/structure/KtModule.kt#L63).).

Also, it should unmute tests using JDK.

**Comment by IgnatBeresnev** [comment]
* Part of analysis API
* Used for setting up the project model
* Alternative in K1: IDE code; K2 has a separate artifact / API.

Without this issue:
* External JVM libraries are not supported; maybe not all
* JDK 8 does no work

Standalone mode - there are Kotlin libraries and Kotlin sources, and different tools need different outputs from it (Symbols, PSIs, etc). The main client of standalone mode is IDE, which needs a lot of non-trivial information. But there are projects where using IDE API is difficult, like Dokka/kapt/ksp - these projects should use standalone API. The main question is "what is this signature?". it's lightweight, very fast. It's more stable because it has 3rd party clients as opposed to IDE internals. Should resolve our problems with IDE dependencies.

Beginning of September, maybe 1.9.20
