### ISSUE TITLE
[Firefox] Strikethrough is placed a little above text

### ISSUE THREAD

**Issue by vmishenev** [Kotlin/dokka#3156]
![image](https://github.com/Kotlin/dokka/assets/9636937/40d2490a-a0c9-4d20-b7d8-4fd5735aaf56)
**Environment**
Dokka 1.9.0
Firefox

**Comment by IgnatBeresnev** [comment]
Cannot reproduce it with Chrome or Safari, but can reproduce it with Firefox, so seems quite specific. 

<details>
<summary>Firefox 116.0.3</summary>

![2023-09-01_17-21-44](https://github.com/Kotlin/dokka/assets/22685910/bbf7f10e-ea0e-489a-b3c0-85cdecc25bda)

</details>

<details>
<summary>Chrome 115.0.5790.170</summary>

![2023-09-01_17-22-59](https://github.com/Kotlin/dokka/assets/22685910/e1504173-7122-4c21-bfe0-81e7c93bb5ac)

</details>

<details>
<summary>Safari 16.5.2</summary>

![safari](https://github.com/Kotlin/dokka/assets/22685910/ef5f85b6-5dbc-456e-89c4-7dd07028ed13)

</details>

If you don't mind, I'll rename the issue slightly to be like #2314, otherwise it looks way too scary when you first see the title :)

**Comment by berezinant** [comment]
Seems like this is a `JetBrains Sans` font peculiarity in firefox. For example:
JetBains Sans (has issue)
<img width="179" alt="JetBrainsSans" src="https://github.com/Kotlin/dokka/assets/4469732/a6f4aac2-b06b-494f-9065-ce7ba7923156">


JetBrains Mono (no issue)
<img width="165" alt="jetbrains mono" src="https://github.com/Kotlin/dokka/assets/4469732/fcbf88e2-ca88-49ef-b740-825a02f47f10">


system-ui (no issue)
<img width="157" alt="system-ui" src="https://github.com/Kotlin/dokka/assets/4469732/ed6e5d8b-4ee8-4f72-a9b7-f34ba7d38c90">

I'm currently not sure if there any chance to influence the issue other than changing the font or altering its source file
