### ISSUE TITLE
WhiteList possibility

### ISSUE THREAD

**Issue by lebedevsd1** [Kotlin/dokka#317]
Hi there,
We want to start using Dokka, but we need whiteList feature.

Is it somewhere on the roadmap? 
for javadoc it was possible to use this configuration:
`
file('documentedClasses.cfg').eachLine {
        line -> include(line)
    }
`

**Comment by semoro** [comment]
It is not planned right now

**Comment by lebedevsd1** [comment]
@semoro it could be also done by https://github.com/Kotlin/dokka/issues/248 signatures

**Comment by IgnatBeresnev** [comment]
I'll close this as a duplicate of https://github.com/Kotlin/dokka/issues/248 since it has more likes and some specific suggestions.

You can implement requested behaviour by creating a custom dokka plugin. There was a request to hide documentation based on annotation/tags, you can use proposed solutions and just reverse the logic, see https://github.com/Kotlin/dokka/issues/2404#issuecomment-1080953576
