### ISSUE TITLE
Javadoc - Markdown support

### ISSUE THREAD

**Issue by yayaa** [Kotlin/dokka#336]
I've seen [the bad news](https://github.com/Kotlin/dokka/issues/170#issuecomment-309394024) about not having doclet implementation for Dokka. This will IMO increase getting more and more requests like this.

But, Markdown would be a common request I assume. Can we have more markdown support on comments? In our specific case, we'd need to use `![](URL)` to display some images.

**Comment by semoro** [comment]
Do you need support for Markdown images in KDoc comments (In kotlin sources) or in Javadoc (java sources)?

**Comment by yayaa** [comment]
I need both, we are trying to replace javadoc usage completely with dokka so to have single tool to produce docs. It needs to work on existing javadoc and also on new KDoc that will be introduced.

**Comment by semoro** [comment]
Support for images in KDoc was requested before (#177), support using markdown for Javadoc isn't planned yet as it non-standard. 
But, at some point, it will be possible to create Dokka plugin that will enable using markdown for Javadoc

**Comment by yayaa** [comment]
I know it's non-standart, we were using a doclet for that... Best thing would be to be able to reuse the doclet we have to produce javadoc, but I've seen in one of the previous issues it is mentioned that will not be supported. IMO, this will make dokka always less configurable than javadoc and will require way more maintaining. 

Anyways, thanks for quick reply, looking forward to have markdown usage.

**Comment by IgnatBeresnev** [comment]
Markdown support for KDoc has been implemented as of now. 

As for markdown in java sources, I don't think it will ever be available "out of the box" since it would introduce more bugs and problems for us to fix, not to say that it goes against the javadoc spec. Moreover, I'd argue that javadoc spec is richer than current generation of KDoc and allows you to do much more with documentation :)

Feel free to create a custom plugin for that though, it should be fairly easy now, see [the documentation](https://kotlin.github.io/dokka/1.6.21/developer_guide/introduction/) for more details
