### ISSUE TITLE
Break down styles.css into separate components files

### ISSUE THREAD

**Issue by berezinant** [Kotlin/dokka#3463]
According to the [spike](https://github.com/Kotlin/dokka/issues/3423) for decomposing styles.css we need to break down styles into separate components to enhance maintainability of styles, simplify development and adding UI components from design

**Comment by IgnatBeresnev** [comment]
Looks like this issue can also be broken down into two parts:
1. (simple) Just physically break down `styles.css` into smaller component-like files. We already have comments in `styles.css` that act as "component sections", so we can use that as a starting point. Here, no renaming, no actual refactoring of the styles and thus no breaking changes are expected.
2. (difficult) Start renaming styles to adhere to the new conventions and [linting rules](#3462), and additionally break down or extract styles to improve maintainability, simplify development and adding of new UI components. This part is difficult because it has a high chance of breaking something, and it might require changes inside Dokka's base plugin (to rename classes, generate additional divs and so on).

Because the second part is difficult, time consuming and needs additional discussion, this issue should focus on the first part.
