### ISSUE TITLE
CI does not run all DGP tests

### ISSUE THREAD

**Issue by adam-enko** [Kotlin/dokka#3805]
CI does not run all tests defined in the dokka-gradle-plugin subproject.

When running `./gradlew test` or `./gradlew check`, this misses tests in DGP, e.g. `:dokka-gradle-plugin:testFunctional`.

Not running all tests leads to failing tests sneaking into master (e.g. https://github.com/Kotlin/dokka/pull/3801)

In similar situations before the Dokka team decided that the build config shouldn't follow Gradle conventions for running tests (The convention is that `check` should run all verifications). Assuming that Dokka should still not follow the conventions, then I'm not sure what the best way forward is.

**Comment by whyoleg** [comment]
AFAIK on current moment we do have `check` depends on both [integration tests](https://github.com/Kotlin/dokka/blob/880ac6527e1208cc867d3ad1f3b78072aac61936/build-logic/src/main/kotlin/dokkabuild.test-integration.gradle.kts#L92-L98) and [functional tests](https://github.com/Kotlin/dokka/blob/d5515e998d19e56e0c5121836a25bc511dddd862/dokka-runners/dokka-gradle-plugin/build.gradle.kts#L204) in Gradle plugin.
I would argue that `test` should depend on `testFunctional`.

> In similar situations before the Dokka team decided that the build config shouldn't follow Gradle conventions for running tests (The convention is that check should run all verifications). Assuming that Dokka should still not follow the conventions, then I'm not sure what the best way forward is.

IMO current situation clearly show that we need to remove dependency of `check` on `integration tests` so that we can easily use just `check` on CI (both TC and GA) by default and continue having separate TC workflow for integration tests for both K1 and K2 analysis. This is inline with how maintainers are working with Dokka - no need to run integration tests in day-to-day workflow.
It's fine to have `:dokka-integration-tests:check` to run integration tests, though root `check/build` should not run them. I thin that here we are not violating any "Gradle conventions" as `dokka-integration-tests` is an included build for a reason and could have different lifecycle comparing to the whole other build.
WDYT?

**Comment by adam-enko** [comment]
Sorry, I'm still not understanding the reasoning. If you want to do something unconventional, then go ahead, but I can't help. What's important is that the tests run on CI.
