### ISSUE TITLE
Please publish the plugin to maven central

### ISSUE THREAD

**Issue by mhshams** [Kotlin/dokka#41]
It would be nice to have the plugin in maven central repository

**Comment by io7m** [comment]
I can assist with this, if necessary.

**Comment by vietj** [comment]
yes, please no kidding

**Comment by jangalinski** [comment]
This really would be a great enhancement. Background: in an enterprise project, we have limited access to "the web" (via proxy) and thus cannot not arbitrary use the repositories-config in a pom, it will not be reachable. And we cannot just add a "less popular" repo like jcenter/bintray/... to company-central  nexus since we do not have permissions. Currently, we just cannot use the plugin. Its not that hard and I also could assist or even run this on our jenkins if required.

**Comment by benjamin-bader** [comment]
Please do publish dokka to Maven Central.

My company does not support JFrog for ethical reasons, and unfortunately that means we cannot make use of this plugin until it's at least hosted somewhere in addition to jcenter.

Thanks!

**Comment by hannesa2** [comment]
"JFrog for ethical reasons" .... I'm interested in what your company reason to give them the attribute not-supportable

**Comment by benjamin-bader** [comment]
I can sum it up by saying, "We choose not to do business with jerks".  I don't expect others to follow suit, but that's the position.

**Comment by sdeleuze** [comment]
Could we please move forward on this issue and publish Dokka 1.4.10+ artifacts to Maven Central? That would simplify the setup in Spring Framework [where we are about to use it](https://github.com/spring-projects/spring-framework/issues/25573), but also in other Spring projects.

Since you chose to use Kotlin versioning (despite the alpha status), current lack of deployment in Central produces IMO unnecessary noise. The fact that Dokka needs to be used both on plugins and dependency side make this even more needed. Also I don't think artifact names are likely to change so that's another reason for such move.

Notice that probably means that transitive dependencies like kotlinx.html should be published on Central as well.

**Comment by hannesa2** [comment]
Is this an option ? https://jitpack.io/#Kotlin/dokka/1.4.0

**Comment by sdeleuze** [comment]
@hannesa2 I don't think Jitpack will help here, Dokka package are already available from Bintray.

More details about the issue I face:
 - I can't use JCenter because it overlaps with Maven Central which is a no go for us
 - I tried to specify individual repositories with https://dl.bintray.com/kotlin/dokka and https://dl.bintray.com/kotlin/kotlinx.html
 - `Could not find org.jetbrains.kotlinx:kotlinx-html-jvm:0.7.2` because https://dl.bintray.com/kotlin/kotlinx.html only contains 0.7.1 versions and previous not 0.7.2
- Ok so I update the repo to the new one https://kotlin.bintray.com/kotlinx
- New error `Could not find org.jetbrains:markdown:0.1.45`

Add to this the fact that it is pretty hard to understand why repositories for a  Gradle plugin should be specified in `repositories { }` in addition to `pluginManagement { repositories { } }`.  Should I create an issue for that or is it something impossible to change?

So please, fix this (you can shade those transitive dependencies if you don't want to publish them to Central) and deploy upcoming release of Dokka 1.4 to Central.

**Comment by ZacSweers** [comment]
Ethical issues aside, jcenter has exhibited reliability issues over the years due to artifact integrity concerns and a general lax security around package uploads (https://blog.autsoft.hu/a-confusing-dependency/). It's not just a matter of preference, but rather that every consumer of Dokka has to add this extra gradle ceremony just to _safely_ add jcenter.

```kotlin
repositories {
  //... other repos
  exclusiveContent {
    forRepository {
      maven {
        name = "JCenter"
        setUrl("https://jcenter.bintray.com/")
      }
    }
    filter {
      // Required for Dokka
      includeModule("org.jetbrains.kotlinx", "kotlinx-html-jvm")
      includeGroup("org.jetbrains.dokka")
      includeModule("org.jetbrains", "markdown")
    }
  }
}
```

**Comment by ibauersachs** [comment]
1.4.10.2 appeared on Maven Central today, but at least `org.jetbrains:markdown` as a required dependency is also not available.

**Comment by ZacSweers** [comment]
1.4.20 however did not make it to maven central

**Comment by DanySK** [comment]
I think Dokka also depends on Korte, which is not on Central yet Korlibs/Korte#13.
Also, JFrog is shutting down bintray in May.

**Comment by mkrussel77** [comment]
Any thought on upgrading to newer `org.jetbrains:markdown` version that is on Maven Central?

**Comment by dnault** [comment]
Might be time to revisit this issue, since JCenter is going offline on May 1st 2021.

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by MarcinAman** [comment]
@mkrussel77 Right now all versions should be on maven central (older and newer). Also dokka was bumped to use the latest

**Comment by juergenzimmermann** [comment]
@MarcinAman When I invoke `gradle buildEnvironment` the output shows the following, and `org.jetbrains.kotlinx:kotlinx-html-jvm` isn't available at Maven Central :-(

```
dokkaGfmPlugin
\--- org.jetbrains.dokka:dokka-base:1.4.20
     +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.4.20
     ...
     +--- org.jetbrains.kotlinx:kotlinx-html-jvm:0.7.2
```

**Comment by MarcinAman** [comment]
@juergenzimmermann Yes, the library authors are working on migration ☺️

**Comment by juergenzimmermann** [comment]
Here is the according issue https://github.com/Kotlin/kotlinx.html/issues/173

**Comment by soywiz** [comment]
KorTE 2.0.7 is on central https://github.com/korlibs/korte/releases/tag/v2.0.7

**Comment by colinrtwhite** [comment]
Have non-alpha versions of the plugin (0.10.x) been moved to maven central? Currently it looks like only `1.4.x` alpha versions [have been migrated](https://mvnrepository.com/artifact/org.jetbrains.dokka/dokka-gradle-plugin).

**Comment by MarcinAman** [comment]
Right now they are not but most of them will be ☺️

**Comment by MarcinAman** [comment]
Closing since 1.4.30 is fully on maven central, including all dependencies 💯
