### ISSUE TITLE
javadoc output is very slow

### ISSUE THREAD

**Issue by martinbonnin** [Kotlin/dokka#506]
I'm using dokka 0.9.17 to generate javadoc on a ~30k kotlin lines Android project. It currently takes ~30min on my machine. If I remove `outputFormat=javadoc`, it's back to a more acceptable ~3min.

Running a profiler gives this:
![Screenshot at 2019-10-02 16-51-13](https://user-images.githubusercontent.com/3974977/66057408-ef771980-e538-11e9-80c7-f92883b1a55e.png)

Is there anything I can do to speedup Javadoc generation ?

**Comment by kamilok1965** [comment]
I'm afraid there's nothing we can do about that. The javadoc generation is delegated to the JDK Doclet, so it most probably is its fault. For the javadoc dokka only wraps the classes extracted form the Kotlin compiler and passes them to the Doclet

**Comment by martinbonnin** [comment]
Could that be parralelized maybe ? It looks like it runs on only one CPU at a time.

**Comment by kamilok1965** [comment]
I don't think so. Since the analysis and wrapping is quite fast (less than 3 minutes in your case, as it seems), that leaves us only the Doclet. There's only one entry point that I'm aware of (namely         HtmlDoclet.start()) which we use, so there's nothing we can do. Probably we could write our own Doclet implementation but it's a hard task and would require considerable amount of time and work, so we don't plan to do that in the nearest future

**Comment by Kordyjan** [comment]
This issue was about an old javadoc renderer. The new one introduced in 1.4.0-rc is no longer depending on Doclet api and should be much faster.
