### ISSUE TITLE
Configuration in separate file is not working with Kotlin Gradle DSL

### ISSUE THREAD

**Issue by petersamokhin** [Kotlin/dokka#819]
I have the Kotlin Multiplatform project with a few modules, but the issue isn't related to type of the project.

Then I decided to rewrite the two last scripts from groovy to kotlin, and everything failed.

**To Reproduce**
https://github.com/petersamokhin/dokka-issue-reproduce

All the gradle configuration files have detailed comments.
See the README with all the ways explained. 
For now, the only working variant is groovy script with 0.9.18 version.
i.e. 0.10.+ versions don't support the multimodule projects, and the kotlin gradle dsl is failing with the Kotlin NPE before my code evaluated.

**Dokka configuration**
Available in the demo project.
And also it doesn't matter. Gradle failed before the configuration block begins.

**Installation**
- Operating system: `macOS 10.15.3 (19D76)`, Ubuntu 18.04.
- Build tool: `gradle-6.3-all`
- Dokka version: `0.10.1`
- Kotlin: `1.3.72`

**Comment by kamildoleglo** [comment]
Hi, sorry for the late reply. 
I believe that this is a Gradle limitation for type-safe accessors (I'm not 100% sure if we can do something about it):  https://docs.gradle.org/current/userguide/kotlin_dsl.html#type-safe-accessors
It worked with Groovy because of its dynamic reflection. The easiest solution that I can think of would be just to configure dokka in each subproject buildscript
